配置代码风格检查
DjangoStudyTeam/django-China-api pull request #22
Opened 2021-12-02 08:52 UTC by s649821022

配置代码风格检查

2021-12-02 08:53 UTC, s649821022 commented
配置代码风格检查(#21 )

2021-12-06 04:37 UTC, jukanntenn requested changes

2021-12-06 04:37 UTC, jukanntenn commented on pyproject.toml
> +isort = "^5.10.1"
这些依赖仅在开发时使用的，因此应该加入到 dev dependency 中。

2021-12-06 14:58 UTC, jukanntenn approved these changes

2021-12-07 01:24 UTC, merged