新增评论通知模块
DjangoStudyTeam/django-China-api pull request #38
Opened 2022-03-17 05:23 UTC by s649821022

新增评论通知模块(#37 )

2022-03-17 13:42 UTC, jukanntenn requested changes

2022-03-17 13:42 UTC, jukanntenn commented on api/apps/notifications/models.py
> +    action_object_content_type = models.ForeignKey(
`recipient` 和 `action_object_content_type` 在 `AbstractNotification` 中已经定义了，为什么再重复定义呢？

2022-03-17 13:42 UTC, jukanntenn commented on api/apps/notifications/models.py
> +    class Meta:
这里也是，在基类中已经定义了，如果要拓展更多的定义，可以这样子：
```
class Meta(AbstractNotification.Meta):
    ...
```
也就是继承 AbstractNotification.Meta

2022-03-17 13:42 UTC, jukanntenn commented on api/apps/notifications/serializers.py
> +from notifications_plus.serializers import NotificationListSerializer
create notification 是多余的，想一想，通知是系统发送给用户的，在什么场景下用户需要自己创建通知呢？

2022-03-17 13:42 UTC, jukanntenn commented on api/apps/notifications/views.py
> +class NotificationCreateViewSet(mixins.CreateModelMixin, NotificationViewSet):
默认的 NotificationViewSet 目前足够用了，可以先继承一下但什么都不做，留到后续根据业务需求再拓展。

2022-03-17 13:42 UTC, jukanntenn commented on config/settings/common.py
还漏了一个重要的配置：NOTIFICATIONS_PLUS_NOTIFICATION_MODEL，要把这个值指向我们自定义的 Notification 模型。

2022-03-17 13:42 UTC, jukanntenn commented on api/apps/comments/signals.py
> +@receiver(post_save, sender=Comment, dispatch_uid="my_unique_identifier")
comment 被创建时，有自己的 signal：comment_posted。监听这个好一些。

2022-03-17 13:42 UTC, jukanntenn commented on api/apps/comments/signals.py
> +    Notification.objects.create(content=f"{instance.user} give you a comment", recipient=instance.user)
这里的逻辑就是要在数据库中创建一条 Notification 记录，所以要捋清 Notification 各个字段应该设置成哪些值。举个例子，recipient 代表这条通知的接受者，那么应该是谁应该接收这条通知呢？显然应该是被评论的人，也就是帖子的作者。这条通知是谁发起的呢？应该是评论者。

2022-03-21 04:41 UTC, jukanntenn requested changes

2022-03-21 04:41 UTC, jukanntenn commented on api/apps/comments/apps.py
> +    def ready(self):
尽管是在为 comment 创建通知，但其实主要的业务逻辑在于“通知”而不是“comment”，所以应该尽量不要改变 comments app，因为 comments app 已经暴露 notification 所需要的全部接口。

2022-03-21 04:41 UTC, jukanntenn commented on api/apps/comments/signals.py
> +def my_handler(sender, instance, content_type, **kwargs):
同上。将这里的业务逻辑移到 notifications.signal 里，并且可以为 `my_handler` 取一个更有意义的名字，例如 `comment_posted_handler`。

2022-03-21 04:41 UTC, jukanntenn commented on api/apps/comments/views.py
>  class CommentCreateUpdateViewSet(TreeCommentCreateUpdateViewSet):
同上。视图函数似乎不需要做任何改变的。

2022-03-21 04:41 UTC, jukanntenn commented on api/apps/notifications/migrations/0001_initial.py
> +# Generated by Django 3.2.8 on 2022-03-18 06:33
单元测试报错的问题，可以试着把 migrations/ 下的文件删除，然后删除数据库文件，再运行 makemigrations 重新生成。

2022-03-21 04:41 UTC, jukanntenn commented on api/apps/comments/signals.py
> +def my_handler(sender, instance, content_type, **kwargs):
可以看看 comment 中 signal 发射的代码：
```
signals.comment_posted.send(
            sender=instance.__class__,
            comment=instance,
            request=self.request,
        )
```
参数为 sender，comment 和 request。
所以 comment_posted_handler 比较合理的函数签名是：
```python
def comment_posted_handler(sender, comment, request):
```
业务逻辑是：
获取 Comment 的 content type，django 提供了一个 api 叫做 get_for_model，这个方法接收一个 Model 作为参数，返回这个 Model 对应的 Content type 记录。参考文档在这里：https://docs.djangoproject.com/en/4.0/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentTypeManager.get_for_model
创建 Notification 记录。content 可以为空。actor 是评论发起人，comment.user 和 request.user 都是可以的。action_object 希望设置为 comment，因此 action_object_content_type 是上面 get_for_model 返回的 comment 的 content type 记录，action_object_object_id 是 comment 的 id。

2022-03-22 13:44 UTC, jukanntenn requested changes

2022-03-22 13:44 UTC, jukanntenn commented on api/apps/comments/serializers.py
> +        model = Comment
`model = Comment` 的声明应该是多余的，因为在基类里面已经声明了：
```
   class Meta:
        model = CommentModel
```

2022-03-22 13:44 UTC, jukanntenn commented on api/apps/notifications/views.py
> +class NotificationCreateViewSet(NotificationViewSet):
这里 `NotificationCreateViewSet ` 命名不太合适，因为这个视图集主要提供查询 API。一个技巧是导入基类 NotificationViewSet 时使用 as 对其重命名，例如 from notifications_plus.viewsets import NotificationViewSet as _NotificationViewSet

然后就可以使用 NotificationViewSet：
```
class NotificationViewSet(_NotificationViewSet):
```

2022-03-22 13:44 UTC, jukanntenn commented on config/settings/common.py
>  TREE_COMMENT_MODEL = "comments.Comment"
这个配置项应该可以删除了，已被 TREE_COMMENTS_TREE_COMMENT_MODEL 取代

2022-03-22 13:44 UTC, jukanntenn commented on config/settings/common.py
> +TREE_COMMENTS_COMMENT_MODEL = "comments.Comment"
这个配置项应该可以删除了，已被 TREE_COMMENTS_TREE_COMMENT_MODEL 取代

2022-03-22 13:47 UTC, jukanntenn commented
代码方面只要再做一点小修改就可以了。接下来就是补充单元测试，测试的思路是发布一条评论，然后检查数据库中产生了一条 Notification，且这条 Notification 的各个字段的值符合预期的结果。

2022-03-23 02:24 UTC, s649821022 commented on api/apps/comments/serializers.py
> +        model = Comment
这个是之前调试的时候加的，忘记删除了

2022-03-23 02:37 UTC, s649821022 commented on config/settings/common.py
> +TREE_COMMENTS_COMMENT_MODEL = "comments.Comment"
这个删除不了，删除会报以下错误：`comments.Comment.user: (fields.E304) Reverse accessor for 'comments.Comment.user' clashes with reverse accessor for 'tree_comments.TreeComment.user'.
	HINT: Add or change a related_name argument to the definition for 'comments.Comment.user' or 'tree_comments.TreeComment.user'.
`

2022-03-23 04:28 UTC, jukanntenn commented on config/settings/common.py
> +TREE_COMMENTS_COMMENT_MODEL = "comments.Comment"
嗯，那应该是之前的 migrations 文件的问题，那就先不管吧。

2022-05-08 11:42 UTC, merged